### PR TITLE
Add dependencies directory for static linking and cross compiling

### PR DESCRIPTION
**Pull request by smogm**
This PR fixes the issue #39.

For example the following bash script will build bitbayd for aarch64 (arm64 e.g. rapsberry pi 3):

```
#!/bin/bash

ARCH="aarch64-linux-gnu"
REPO="https://github.com/bitbaymarket/bitbay-core.git"

git clone $REPO
cd $(basename $REPO .git)

chmod -R 755 .

cd depends

make HOST=$ARCH NO_QT=1 NO_UPNP=1 -j4

cd ..

./autogen.sh

./configure --prefix=$(pwd)/depends/$ARCH --with-gui=no --without-miniupnpc --enable-reduce-exports --disable-tests --disable-gui-tests --disable-bench

make -j2
```

Resulting `bitbayd`:

```
$ file src/bitbayd
src/bitbayd: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=844ddba8bd5588cbf7c39285e8a9fd82b81f9df5, not stripped
```

### CODE REVIEW

**Comment by yshurik** [comment]
Hi,
It did not pass github checks in travis and appveyor.
There are massive changes in leveldb - what are they based on and how can be tested? - is it different version of leveldb?

**Comment by smogm** [comment]
Sorry for this issue. I tried to integrate a newer version of leveldb. But it seems it does not comply with the older mingw version you are using for AppVeyor. The newer leveldb uses some intrinsic code parts to speed up calculations, which is not provided in this mingw header files.

The current bitbay-core code looks - with all the various bash scripts and pre-compiled libs - in general very provisional and unhandsome.
Maybe we should try to bring it up to a more flexible and modern level?

**Comment by yshurik** [comment]
It is planned to be updated very soon. The build system is planned to be docker based. Also some clean-up will be done. Thanks for the issue and merge request. If you rollback all changes to sources and keep only "depends" addons (I guess you agree to have only one thing at the time) then it should be ok to review after all checks pass. 
Regarding RPi, the leveldb is new enough (1.20, see #5), and was successfully tested on RPi. 
Also you referred output from "file src/bitbayd", it is good to show also output of "ldd src/bitbayd"

**Comment by smogm** [comment]
Reverted leveldb.
Only depends and makefile.am are added (no conflicts with existing make/build procedure).

`$ ldd src/bitbayd
not a dynamic executable`

**Comment by smogm** [comment]
Btw: recent build failed due to 404 error while getting java from a oracle server: https://travis-ci.org/bitbaymarket/bitbay-core/jobs/520919848#L1046

```
Connecting to download.oracle.com (download.oracle.com)|104.91.198.243|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz?AuthParam=1555491360_5c8be80ca8d1e5173c3714c18cd718c7 [following]
--2019-04-17 08:54:00--  https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz?AuthParam=1555491360_5c8be80ca8d1e5173c3714c18cd718c7
Connecting to download.oracle.com (download.oracle.com)|104.91.198.243|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-17 08:54:00 ERROR 404: Not Found.
download failed
Oracle JDK 8 is NOT installed.
dpkg: error processing package oracle-java8-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up libgcc-4.8-dev:i386 (4.8.4-2ubuntu1~14.04.4) ...
Setting up linux-libc-dev:amd64 (3.13.0-168.218) ...
Setting up linux-libc-dev:i386 (3.13.0-168.218) ...
Setting up libc6-dev:i386 (2.19-0ubuntu6.15) ...
Setting up libstdc++-4.8-dev:i386 (4.8.4-2ubuntu1~14.04.4) ...
Setting up libboost1.54-dev (1.54.0-4ubuntu3.1) ...
Setting up libboost-system1.54-dev:i386 (1.54.0-4ubuntu3.1) ...
Setting up libboost-filesystem1.54-dev:i386 (1.54.0-4ubuntu3.1) ...
Setting up libboost-filesystem-dev:i386 (1.54.0.1ubuntu1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
Errors were encountered while processing:
 oracle-java8-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by yshurik** [comment]
Please remove all files in build-aux except m4 folder

It is supposed to be empty: https://github.com/bitcoin/bitcoin/tree/master/build-aux/

These files are auto-created during build and not supposed to be in git

So far it is good:

gentoo x64 - ok
gentoo x86 - ok
ubuntu trusty - ok
rpi2 - ok

**Comment by smogm** [comment]
@yshurik sorry for the inconvenience.
Should be fine by now!

**Pull request merged**
